blank_issues_enabled: true
contact_links:
  - name: 📌 Frequently Asked Questions
    url: https://filoghost.me/docs/chest-commands/faq
    about: Please read the FAQ before opening any kind of issue.
